#! /usr/bin/python3

"""
Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted.
THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
"""

import json
import requests
import copy
import csv
import argparse

# Hardcoded constants
RESOURCE_XRD = "resource_rdx1tknxxxxxxxxxradxrdxxxxxxxxx009923554798xxxxxxxxxradxrd"

# Parse command line args
cmdlineParser = argparse.ArgumentParser(
	prog='radix-analyzeRoot.py',
	description='Analyzes the state of the Root Finance lending market on Radix.')

cmdlineParser.add_argument('-o', '--output_file', default="root-cdps.csv")
cmdlineParser.add_argument('-p', '--preset', default="")
cmdlineParser.add_argument('-g', '--gateway', default="http://127.0.0.1:5001/")

args = cmdlineParser.parse_args()



# TODO: Fetch current prices from somewhere instead of hardcoding them.
priceUsd = 1.
priceBtc = 67393.
priceEth = 1942.32000
priceXrd = 0.00254
priceLSULP = 1.1857 * priceXrd 
priceHug   = .0001605 * priceXrd
priceEarly = .04070 * priceXrd
priceWowo  = .03392 * priceXrd
pricesOK = False # set to True if you want to use the prices specified above

ledgerState_query = None # most recent

# Historical data
preset_queryHistoricalState = args.preset

if preset_queryHistoricalState == "Preset-2026-02-22T19:00Z":
	ledgerState_query = { "timestamp" : "2026-02-22T19:00:00Z" }
	priceUsd = 1.
	priceBtc = 67393.
	priceEth = 1942.32000
	priceXrd = 0.00254
	priceLSULP = 1.1857 * priceXrd 
	priceHug   = .0001605 * priceXrd
	priceEarly = .04070 * priceXrd
	priceWowo  = .03392 * priceXrd
	pricesOK = True

elif preset_queryHistoricalState == "Preset-2026-02-22T00:00Z":
	ledgerState_query = { "timestamp" : "2026-02-22T00:00:00Z" }
	priceUsd = 1.
	priceBtc = 67966.
	priceEth = 1973.
	priceXrd = .002412
	priceLSULP = 1.1857 * priceXrd 
	priceHug   = .0001605 * priceXrd
	priceEarly = .04040 * priceXrd
	priceWowo  = .03551 * priceXrd
	pricesOK = True
	
elif preset_queryHistoricalState == "Preset-2026-02-15T00:00Z":
	ledgerState_query = { "timestamp" : "2026-02-15T00:00:00Z" }
	priceUsd = 1.
	priceBtc = 69787.
	priceEth = 2085.40000
	priceXrd = 0.00165
	priceLSULP = 1.1826 * priceXrd 
	priceHug   = .0001990 * priceXrd
	priceEarly = .04281 * priceXrd
	priceWowo  = .03380 * priceXrd
	pricesOK = True

elif preset_queryHistoricalState == "2025EOY":
	ledgerState_query = { "timestamp" : "2026-01-01T00:00:00Z" }
	priceUsd = 1.
	priceBtc = 87496.000000
	priceEth = 2966.840000
	priceXrd = 0.001491
	priceLSULP = 1.1733 * priceXrd 
	priceHug   = .0001629 * priceXrd
	priceEarly = .03159 * priceXrd
	priceWowo  = .02727 * priceXrd
	pricesOK = True
		
elif preset_queryHistoricalState == "2024EOY":
	ledgerState_query = { "timestamp" : "2025-01-01T00:00:00Z" }
	priceUsd = 1.
	priceBtc = 93381.000000
	priceEth = 3330.320000
	priceXrd = 0.022606
	priceLSULP = 1.0972 * priceXrd 
	priceHug   = .001133 * priceXrd
	priceEarly = .1562 * priceXrd
	priceWowo  = .02887 * priceXrd
	pricesOK = True

elif preset_queryHistoricalState != "":
	raise ValueError(f"Invalid historical preset: {preset_queryHistoricalState}")

if not pricesOK:
	raise RuntimeError(f"No valid price data set!")


print("#### CDP and Pool analysis of Root Finance on Radix ####")
print("""
WARNING: This report was generated by experimental software.
The data in this report may have errors, might be incomplete and might even be entirely incorrect.
""")




pricelist = [
	["USD", priceUsd],
	["BTC", priceBtc],
	["ETH", priceEth],
	["XRD", priceXrd],
	["LSULP", priceLSULP],
	["HUG", priceHug],
	["EARLY", priceEarly],
	["WOWO", priceWowo] ]
strPricelist = "".join(["{:>5s}: {:.6g}\n".format(lbl, p) for lbl, p in pricelist])
print("**** USD prices used for analysis ****\n" + strPricelist)
	
gateway = args.gateway

if gateway[-1] == "/":
	gateway = gateway[:-1]

if gateway[:7] != "http://" and gateway[:8] != "https://":
	raise RuntimeError(f"Bad gateway address: {gateway}")


def fetchData(url):
	resp = requests.get(url)
	return resp.json()
		
# Helper function for pretty-printing Dictionaries. Useful for debugging.
def prettyJson(x):
	return json.dumps(x, indent=4)

# Helper function for pretty-printing Dictionaries. Useful for debugging.	
def prettyPrint(x):
	print(prettyJson(x))

def callRadixGateway(method, params = None):
	method = method.strip('?%:')
	url = "{}/{}".format(gateway, method)
	payload = json.dumps(params)
	headers = {'content-type': "application/json", 'cache-control': "no-cache"}
	try:
		response = requests.request("POST", url, data=payload, headers=headers)  #, auth=(rpc_user, rpc_password))
# 		print("Radix Gateway raw response: {}".format(response.text))
		jsonResponse = json.loads(response.text)
		jsonErrorType = jsonResponse.get("error_type")
		jsonErrorMessage = jsonResponse.get("message")
		jsonErrorTrace = jsonResponse.get("trace_id")
		if jsonErrorType is not None:
			raise Exception("RPC call failed with error {errortype}, trace {trace}: {msg}".format(
				errortype=jsonErrorType, trace=jsonErrorTrace, msg=jsonErrorMessage))
		return jsonResponse
		
	except requests.exceptions.RequestException as e:
		print(e)
	except:
		print ('Radix Gateway RPC call failed, check if radix gateway is running on this machine')
		raise
		
def boolmoji(v): return "✅️" if v else "❌️"

class TypedValue:
	def __init(self):
		self.value = None
		self.kind = None
		self.type_name = None
		
	def __init__(self, value, kind, type_name):
		self.value = value
		self.kind = kind
		self.type_name = type_name
		
	def isDictKind(self):
		return self.kind == "Tuple" or self.kind == "Map" # TODO: Map should be treated differently
		
		
	def toString(self, indent=0):
		#result = "\t" * int(indent)
		printedValue = "??????"
		
		if self.isDictKind():
			printedValue = "** {} named entries **".format(len(self.value))
		elif self.kind == "Bool" and type(self.value) == bool:
			printedValue = boolmoji(self.value)
		else:
			printedValue = str(self.value)
		
		printedTypename = "{}: ".format(self.type_name) if self.type_name is not None else ""
		
		result = "({kind}) {typename}{value}".format(kind=self.kind, typename=printedTypename, value=printedValue)
		if self.isDictKind():
			indent += 1
			for k, v in self.value.items():
				result += "\n" + "\t"*indent + "{k} = {v}".format(k=k, v=v.toString(indent))
		return result
		
	def __str__(self):
		return self.toString()
		
	def __getitem__(self, idx):
		return self.value[idx]
				
		
		
def parseTypedValue(jsonIn):
	#print("{} {}".format(jsonIn.get("kind"), jsonIn.get("field_name")))
	kind = jsonIn["kind"]
	value = None
	if kind == "Tuple":
		value = parseFieldsList(jsonIn["fields"])
	elif kind == "Enum":
		value = jsonIn["fields"]
	elif kind == "Map":
		value = parseMap(jsonIn["entries"])
	else:
		value = jsonIn["value"]
			
	return TypedValue(value = value, kind = kind, type_name = jsonIn.get("type_name"))


def parseFieldsList(jsonIn):
	result = {}
	for f in jsonIn:
		result[f["field_name"]] = parseTypedValue(f)
	return result
	
def parseMap(jsonIn):
	# TODO do it properly!
	result = {}
	for f in jsonIn:
		k = f["key"] # TODO: the key is a TypedValue and should really be parsed as such
		v = f["value"]		
		result[str(k["value"])] = parseTypedValue(v)
	return result

		
class FungibleResource:
	def __init__(self, address):
		self.address = address
		self.balance = 0.
		self.name = ""
		self.ticker = ""
		self.supply = None
		self.amountMinted = None
		self.amountBurned = None
				
		self.price = 0.
		self.root_loanUnitValue = 0.
		self.root_depositUnitValue = 0.
		self.root_internalUnitToAssetRatio = None


class WatchedAccount:
	def __init__(self, label, address):
		self.label = label
		self.address = address
		self.txids = []
		self.numFTs = 0
		self.numNFTs = 0
		self.balanceXRD = 0.  # liquid XRD
		self.balanceFungiblesByAddress = {}
		self.details = None
		self.state = None
		
		self.root_addrPoolUnit = None
		self.root_externalLiquidityAmount = None
		self.root_unitToAssetRatio = None # Pool units per unit of asset. Should be <=1. Should be >0 for non-empty pools
	
	def isRootFinancePool(self): 
		return self.root_addrPoolUnit is not None
		
	def populateAccountDetailsFromGatewayResponse(self, detailsItem):
		global RESOURCE_XRD
		if detailsItem["address"] != self.address:
			raise Exception("Attempted to populate account details for '{}' with API object belonging to '{}'.".format(
				self.address,
				detailsItem["address"]))
		self.numFTs = int(detailsItem["fungible_resources"]["total_count"])
		self.numNFTs = int(detailsItem["non_fungible_resources"]["total_count"])
		self.balanceXRD = 0.
		self.balanceXRD = 0.
		for fungible in detailsItem["fungible_resources"]["items"]:
			self.balanceFungiblesByAddress[fungible["resource_address"]] = float(fungible["amount"])
			if fungible["resource_address"] == RESOURCE_XRD:
				self.balanceXRD += float(fungible["amount"])	
		self.details = detailsItem["details"]
		self.state = parseTypedValue(self.details["state"])
		
		if self.details["package_address"] == "package_rdx1pkhvtjl4m968u3jlxmehnszxwn0kzake49wvfw4x45lu43eqm96c80" and self.details["blueprint_name"] == "SingleResourcePool" :
			self.root_addrPoolUnit = str(self.state["pool_unit_res_manager"].value)
			self.root_unitToAssetRatio = float(self.state["unit_to_asset_ratio"].value)
			self.root_externalLiquidityAmount = float(self.state["external_liquidity_amount"].value)



	
def downloadKeyValueStore(kvaddr, ledgerState = None):
	gatewayArgs = {"key_value_store_address" : kvaddr }
	if ledgerState is not None:
		gatewayArgs["at_ledger_state"] = ledgerState

	# Quick & Dirty
	keysRaw = callRadixGateway("state/key-value-store/keys", gatewayArgs)
	#prettyPrint(keysRaw)
	keys = [ {"key_hex" : item["key"]["raw_hex"] } for item in keysRaw["items"] ]
	#print(keys)
	names = [ item["key"]["programmatic_json"]["value"] for item in keysRaw["items"] ]
	#WARNING need to add pagination, can request max 100 values at once
	
	gatewayArgs["keys"] = keys
	valuesRaw = callRadixGateway("state/key-value-store/data", gatewayArgs)
	return valuesRaw






# ----- Preparations -----



fungibles = {}
debugmode = False

print("\n**** Current gateway status ****")
radixGatewayStatus = callRadixGateway("status/gateway-status")
prettyPrint(radixGatewayStatus)

if ledgerState_query is None:
	ledgerState_query = {"state_version": radixGatewayStatus["ledger_state"]["state_version"] }

addrEntity = "component_rdx1crwusgp2uy9qkzje9cqj6pdpx84y94ss8pe7vehge3dg54evu29wtq" # Root Finance lending market component
addrState = "internal_keyvaluestore_rdx1kr9pe655r6gvkemdnwd2588pkfs8nz0ds0depfzpr65grz4e77hnju" # Root Finance lending market component



# ----- Fetch lending market state and all involved fungibles -----



#print("### ENTITY DETAILS FOR {} ###".format(addrEntity))
#details = callRadixGateway("state/entity/details", {"addresses": ["resource_rdx1ngekvyag42r0xkhy2ds08fcl7f2ncgc0g74yg6wpeeyc4vtj03sa9f"]})
#prettyPrint(details)

kv = downloadKeyValueStore(addrState, ledgerState_query)
ledgerState_response = None

# Grab asset data for all fungible assets that have a Root lending pool.
for entry in kv["entries"]:
	entryKey = parseTypedValue(entry["key"]["programmatic_json"])
	if entryKey.kind == "Reference" and entryKey.type_name == "ResourceAddress" and entryKey.value[:9] == "resource_":
		addr = entryKey.value
		fungibles[addr] = FungibleResource(addr)

nResourcesPerBatch = 20
for i in range(0, len(fungibles), nResourcesPerBatch):
	fungiblesSlice = list(fungibles.values())[i:i+nResourcesPerBatch]
	response = callRadixGateway("state/entity/details", {
		"at_ledger_state" : ledgerState_query, 
		"addresses": [ft.address for ft in fungiblesSlice]
	})
	ledgerState_response = response["ledger_state"]
	responseCount = len(response["items"])
	if responseCount != len(fungiblesSlice):
		raise Exception("Bad response from Radix Gateway: Got {} items, expected {} items".format(
			len(response["items"]), len(fungiblesSlice)))
	#print(f"Fetched data for {responseCount} fungible assets.")
			
	for j in range(responseCount):
		item = response["items"][j]
		addr = item["address"]
		ft = fungibles[addr]
		
		ft.supply = float(item["details"]["total_supply"])
		ft.amountMinted = float(item["details"]["total_minted"])
		ft.amountBurned = float(item["details"]["total_burned"])
		
		meta = item["metadata"]["items"]
		metaCountTotal = item["metadata"]["total_count"]
		metaCount = len(meta)
		gotAllMeta = metaCount == metaCountTotal
		if not gotAllMeta:
			print(f"### WARNING ### FT {addr}: don't have all metadata, need to implement pagination")
		for m in meta:
			if m["key"] == "name": ft.name = str(m["value"]["typed"]["value"])
			elif m["key"] == "symbol": ft.ticker = str(m["value"]["typed"]["value"])

print("\n**** Ledger state used for this analysis ****")
prettyPrint(ledgerState_response)
print("----------------------------------------\n")

print(f"Got {len(fungibles)} relevant fungible assets:")
for addr, ft in fungibles.items():
	print(f"{addr} : {ft.name}")



priceByFungible = {
	"resource_rdx1th09yvv7tgsrv708ffsgqjjf2mhy84mscmj5jwu4g670fh3e5zgef0" : priceEth, # hETH
	"resource_rdx1th4v03gezwgzkuma6p38lnum8ww8t4ds9nvcrkr2p9ft6kxx3kxvhe" : priceUsd, # hUSDT
	"resource_rdx1thxj9m87sn5cc9ehgp9qxp6vzeqxtce90xm5cp33373tclyp4et4gv" : priceUsd, # hUSDC
	"resource_rdx1t58kkcqdz0mavfz98m98qh9m4jexyl9tacsvlhns6yxs4r6hrm5re5" : priceBtc, # hwBTC
	"resource_rdx1thksg5ng70g9mmy9ne7wz0sc7auzrrwy7fmgcxzel2gvp8pj0xxfmf" : priceLSULP,
	"resource_rdx1t580qxc7upat7lww4l2c4jckacafjeudxj5wpjrrct0p3e82sq4y75" : priceBtc, # xwBTC
	"resource_rdx1tknxxxxxxxxxradxrdxxxxxxxxx009923554798xxxxxxxxxradxrd" : priceXrd,
	"resource_rdx1thrvr3xfs2tarm2dl9emvs26vjqxu6mqvfgvqjne940jv0lnrrg7rw" : priceUsd, # xUSDT
	"resource_rdx1t4upr78guuapv5ept7d7ptekk9mqhy605zgms33mcszen8l9fac8vf" : priceUsd, # xUSDC
	"resource_rdx1t5kmyj54jt85malva7fxdrnpvgfgs623yt7ywdaval25vrdlmnwe97" : priceHug,
	"resource_rdx1t5xv44c0u99z096q00mv74emwmxwjw26m98lwlzq6ddlpe9f5cuc7s" : priceEarly,
	"resource_rdx1t4kc5ljyrwlxvg54s6gnctt7nwwgx89h9r2gvrpm369s23yhzyyzlx" : priceWowo,
	
}

for addr, price in priceByFungible.items():
	ft = fungibles.get(addr)
	if ft is None: continue
	ft.price = price


print("\n\n\n-----ROOT FINANCE POOL STATES-----\n")
#prettyPrint(kv)
print(kv["ledger_state"]["proposer_round_timestamp"])
print("\n--------------------------\n")

	
	
	

# ----- Get state of each individual pool -----

poolStatesByPoolAddr = {}
for i, entry in enumerate(kv["entries"]):
	entryValue = parseTypedValue(entry["value"]["programmatic_json"])
	entryPool = entryValue["pool"].value
	entryTokenName = "*** unknown token ***"
	poolStatesByPoolAddr[entryPool] = WatchedAccount(entryTokenName, entryPool)
	#print("\n{}".format(entryPool))
	
if True:
	keys = []
	for k,v in poolStatesByPoolAddr.items():
		keys.append(k)

	response = callRadixGateway("state/entity/details", {"at_ledger_state" : ledgerState_query, "addresses": keys})
	for j, item in enumerate(response["items"]):
		acc = poolStatesByPoolAddr[item["address"]]
		#prettyPrint(item)
		acc.populateAccountDetailsFromGatewayResponse(item)
	



# --- Analyze the state of all pools ---


totalPoolNetValue = 0.00
totalPoolDepositsValue = 0.00
totalPoolLoansValue = 0.00
totalPoolReservesValue = 0.00
totalPoolReservesValue_byAssetAddress = {}

strPoolStateSummary = "\n***** Root Lending Market Pool state summary *****\n"
strPoolStateSummary += "{token:>10s} : {reserves:13s} + {loan:13s} - {deposit:13s} = {net:13s}        = {netUsd:12s}    \n".format(
		token="Token", reserves = "Reserves", loan="Loans", deposit="Deposits",
		net="Net balance", netUsd = "Net value")
	

for entry in kv["entries"]:
	entryKey = parseTypedValue(entry["key"]["programmatic_json"])
	entryValue = parseTypedValue(entry["value"]["programmatic_json"])
	entryLastUpdateAtState = entry["last_updated_at_state_version"]
	entryIsLocked = entry["is_locked"]
	entryPool = entryValue["pool"].value
	entryResAddr = entryValue["pool_res_address"].value
	acc = poolStatesByPoolAddr[entryPool]
	entryTokenName = "*** unknown token ***"
	
	entryFungible = fungibles.get(entryKey.value)
	if entryFungible is not None:
		entryTokenName = entryFungible.ticker
		
	
		
	
	rekt = float(entryValue["total_loan_unit"].value) < 0.0000001 and float(entryValue["total_loan"].value) > 0.0001
	
	entryLoan = float(entryValue["total_loan"].value)
	entryDeposit = float(entryValue["total_deposit"].value)
	entryLoanUnit = float(entryValue["total_loan_unit"].value)
	entryDepositUnit = float(entryValue["total_deposit_unit"].value)
	
	if entryLoanUnit > 0:
		entryFungible.root_loanUnitValue    = entryLoan / entryLoanUnit
	if entryDepositUnit > 0:
		entryFungible.root_depositUnitValue = entryDeposit / entryDepositUnit 
	if acc.isRootFinancePool():
		entryFungible.root_internalUnitToAssetRatio = acc.root_unitToAssetRatio
	
	entryReserves = float(acc.balanceFungiblesByAddress[entryResAddr])
	entryNetBalance = entryReserves + entryLoan - entryDeposit
	
	entryReservesValue = entryFungible.price * entryReserves
	entryDepositsValue = entryFungible.price * entryDeposit
	entryLoansValue = entryFungible.price * entryLoan
	entryNetValue = entryFungible.price * entryNetBalance
	
	totalPoolReservesValue += entryReservesValue
	totalPoolReservesValue_byAssetAddress[entryKey.value] = entryReservesValue
	
	totalPoolNetValue += float(entryNetValue)
	totalPoolDepositsValue += entryDepositsValue
	totalPoolLoansValue += entryLoansValue
	strPoolStateSummary += "{token:>10s} : {reserves:13.4f} + {loan:13.4f} - {deposit:13.4f} = {net:13.4f} tokens = {netUsd:12.2f} USD\n".format(
		token=entryTokenName, reserves = entryReserves, loan=entryLoan, deposit=entryDeposit,
		net=entryNetBalance, netUsd = entryNetValue)
	
	flags = ""
	if(rekt): flags = " *** WEIRD ZERO LOAN UNIT *** "
	print("\n######### POOL STATE{}: {} ({})\n{} ".format(flags, entryKey, entryTokenName, entryValue))
	
print(strPoolStateSummary)
print("Total pool excess value: {:,.2f} USD".format(totalPoolNetValue))
	






# --- prepare stuff for analyzing individual Root Receipts ---

ADDR_ROOT_RECEIPT = "resource_rdx1ngekvyag42r0xkhy2ds08fcl7f2ncgc0g74yg6wpeeyc4vtj03sa9f"
queryMoreRootReceipts = True
idxNextRootReceipt = 1
nRootReceiptsPerRequest = 100

globalBadDebtValue = 0.
globalRiskyDebtValue = 0.
globalXusdcLoan = 0.
globalXusdcDeposits = 0.

class BalanceSheetEntry:
	def __init__(self, name, assets = 0., liabilities = 0.):
		self.name = name
		self.assets = assets
		self.liabilities = liabilities
	def add(self, assets, liabilities):
		self.assets += assets
		self.liabilities += liabilities

class RootCdpAssetBalances:
	def __init__(self, asset):
		self.assetName = asset.name
		self.assetTicker = asset.ticker
		self.assetAddress = asset.address
		self.collateral = 0.
		self.loan = 0.
		self.value_collateral = 0.
		self.value_loan = 0.

class RootCdp:
	def __init__(self, cdpAssets, nftId):
		self.balances = [ RootCdpAssetBalances(f) for f in cdpAssets ]
		self.balanceByAddress = { b.assetAddress : b for b in self.balances }
		self.nftId = nftId
		self.riskClass = 0
		self.comment = ""
	
	def addCollateral(self, addrAsset, amount, value):
		b = self.balanceByAddress[addrAsset]
		b.collateral += amount
		b.value_collateral += value
		
	def addLoan(self, addrAsset, amount, value):
		b = self.balanceByAddress[addrAsset]
		b.loan -= amount
		b.value_loan -= value
		
	def csvHeaders(self):
		result = []
		tickers = list([b.assetTicker for b in self.balances])
		result.append("cdp id")
		result.extend([f"{t} coll" for t in tickers])
		result.extend([f"{t} loan" for t in tickers])
		result.extend([f"{t} coll value" for t in tickers])
		result.extend([f"{t} loan value" for t in tickers])
		result.extend(["coll total value", "loan total value", "net value"])
		return result
		
	def csvValues(self):
		coll_total_value = sum([b.value_collateral for b in self.balances])
		loan_total_value = sum([b.value_loan for b in self.balances])
		net_value = coll_total_value + loan_total_value
		result = []
		result.append(self.nftId)
		result.extend([str(b.collateral) for b in self.balances])
		result.extend([str(b.loan) for b in self.balances])
		result.extend([str(b.value_collateral) for b in self.balances])
		result.extend([str(b.value_loan) for b in self.balances])
		result.extend([coll_total_value, loan_total_value, net_value])
		return result
	
	def print(self, fungibles):
		nftStatus = ""
		if self.riskClass == 0: nftStatus = "OK"
		elif self.riskClass == 1: nftStatus = "RISKY"
		elif self.riskClass == 2: nftStatus = "*** BAD DEBT ***"
		else: nftStatus = "(Unknown risk class)"
		
		if len(self.comment) > 0:
			nftStatus += f" : {self.comment}"
			
		coll_total_value = sum([b.value_collateral for b in self.balances])
		loan_total_value = sum([b.value_loan for b in self.balances])
		net_value = coll_total_value + loan_total_value
		
		ltv = 0.		
		if coll_total_value == 0.:
			ltv = 99999. if loan_total_value < -1.e-6 else 0.
		else:
			ltv = -loan_total_value / coll_total_value
	
		print("\n----- Root Receipt {nftId} : net {netValue:>13,.2f} USD , LTV {ltv:>6.2f}% : {status} ------".format(
			nftId = nftId,
			netValue = net_value,
			ltv = ltv*100.,
			status = nftStatus))
								
		print("Collaterals: {:>13,.2f} USD".format(coll_total_value))
		for b in self.balances:
			if b.collateral == 0.: continue
			asset = fungibles[b.assetAddress]
			print("    + {value:>13,.2f} USD as {amount:>16,.4f} {name:s}".format(
				amount = b.collateral,
				value = b.value_collateral,
				name = asset.ticker,
				))
				
		print("Loans: {:>13,.2f} USD".format(loan_total_value))
		for b in self.balances:
			if b.loan == 0.: continue
			asset = fungibles[b.assetAddress]
			print("    + {value:>13,.2f} USD as {amount:>16,.4f} {name:s}".format(
				amount = -b.loan,
				value = -b.value_loan,
				name = asset.ticker,
				))
		
		
RISKCLASS_OK = 0
RISKCLASS_RISKY = 1
RISKCLASS_REKT = 2

balanceSheetEntriesByRiskClass = [
	BalanceSheetEntry("Healthy CDPs"),
	BalanceSheetEntry("Risky CDPs"),
	BalanceSheetEntry("Rekt CDPs"), ]

cdpAssets = list(fungibles.values())
cdps = []


# --- fetch and analyze all Root Receipts ---
print("\n***** Root receipts of interest *****")

while queryMoreRootReceipts:
	nftIds = list(range(idxNextRootReceipt, idxNextRootReceipt+nRootReceiptsPerRequest))
	nftIds = ["#{}#".format(x) for x in nftIds]
	response = callRadixGateway("state/non-fungible/data", {"at_ledger_state" : ledgerState_query, "resource_address": ADDR_ROOT_RECEIPT, "non_fungible_ids": nftIds})
	try:
		nfts = response["non_fungible_ids"]
		nfts.reverse()
		for nft in nfts:
			#prettyPrint(nft)
			nftId = str(nft["non_fungible_id"])
			nftData = parseTypedValue(nft["data"]["programmatic_json"])
			
			nftTotalCollateralValue = 0.
			nftTotalLoanValue = 0.
			
			cdp = RootCdp(cdpAssets, nftId)
			cdps.append(cdp)
			
			nftXusdcLoan = 0.
			
			for addrAsset, typedAmountUnits in nftData["collaterals"].value.items():
				amountUnits = float(typedAmountUnits.value)
				asset = fungibles.get(addrAsset)
				if asset is None:
					raise ValueError(f"Unknown asset address: {addrAsset}")
				amount = asset.root_depositUnitValue * amountUnits
				value = asset.price * amount
				nftTotalCollateralValue += value
				
				cdp.addCollateral(addrAsset, amount, value)
					
				if addrAsset == "resource_rdx1t4upr78guuapv5ept7d7ptekk9mqhy605zgms33mcszen8l9fac8vf":	
					globalXusdcDeposits += amount
				
				
					
			for addrAsset, typedAmountUnits in nftData["loans"].value.items():
				amountUnits = float(typedAmountUnits.value)
				asset = fungibles.get(addrAsset)
				if asset is None: 
					raise ValueError(f"Unknown asset address: {addrAsset}")
				amount = asset.root_loanUnitValue * amountUnits
				value = asset.price * amount
				nftTotalLoanValue += value
				
				cdp.addLoan(addrAsset, amount, value)
					
				if addrAsset == "resource_rdx1t4upr78guuapv5ept7d7ptekk9mqhy605zgms33mcszen8l9fac8vf":
					nftXusdcLoan += amount
					globalXusdcLoan += amount
			
			# Set Risk Class of NFT based on LTV
			riskClass = RISKCLASS_OK
			nftBadDebtValue = max(0., nftTotalLoanValue - nftTotalCollateralValue)
			if nftTotalLoanValue > 1.e-3 and nftBadDebtValue > 0. : 
				riskClass = RISKCLASS_REKT
			elif nftTotalLoanValue > 1.e-3 and nftTotalLoanValue > .80*nftTotalCollateralValue : 
				riskClass = RISKCLASS_RISKY
				globalRiskyDebtValue += nftTotalLoanValue
				
			cdp.riskClass = riskClass
			globalBadDebtValue += nftBadDebtValue
				
			# From the Root platform's point of view: Loans = Assets , Collateral = Liabilities
			balanceSheetEntriesByRiskClass[riskClass].add(nftTotalLoanValue, nftTotalCollateralValue) 
			
			
			isRootOwnedNft = nftId in ["#1#", "#677#", "#739#"]
			isWeirdNft = nftId in ["#639"] # Meme backed
			printNft = (riskClass != RISKCLASS_OK and nftTotalLoanValue >= 0.10) or isRootOwnedNft or isWeirdNft or nftXusdcLoan > 100.
			
			if isRootOwnedNft: cdp.comment += "(Owned by Root special badge holder)"
			
			if printNft:
				cdp.print(fungibles)
				
		idxNextRootReceipt += nRootReceiptsPerRequest
		if len(nfts) < nRootReceiptsPerRequest : queryMoreRootReceipts = False
	except Exception:
		print("***ERROR***")
		print(response)
		queryMoreRootReceipts = False
		raise
print("\n")
print("{:>13,.2f} USD of bad debt found".format(globalBadDebtValue))
print("{:>13,.2f} USD of risky debt found".format(globalRiskyDebtValue))
print("{:>13,.2f} USD of xUSDC debt found".format(globalXusdcLoan))
print("{:>13,.2f} USD of xUSDC deposits found".format(globalXusdcDeposits))

if True:
	xusdc = fungibles.get("resource_rdx1t4upr78guuapv5ept7d7ptekk9mqhy605zgms33mcszen8l9fac8vf")
	print("xUSDC     loan unit value: {}".format(xusdc.root_loanUnitValue))
	print("xUSDC  deposit unit value: {}".format(xusdc.root_depositUnitValue))
	print("xUSDC internal unit value: {}".format(1./xusdc.root_internalUnitToAssetRatio))


totalProtocolNetValue = totalPoolNetValue - globalBadDebtValue

print("\n*********** VALUE SUMMARY according to Lending Market state ***********\n" +
      "   POOL VALUE: {:>13,.2f} USD\n".format(totalPoolNetValue) +
      "     BAD DEBT: {:>13,.2f} USD\n".format(globalBadDebtValue) +
      "--------------------------------\n" +
      "    NET VALUE: {:>13,.2f} USD\n".format(totalProtocolNetValue) +
      "--------------------------------\n" )
#      "Pool reserves: {:>13,.2f} USD"
      




# ----- Print balance sheets -----



def printBalanceSheetEntry(entry):
	print("{label:>20s}: {assets:>13,.2f} | {liabilities:>13,.2f} || {net:>13,.2f}".format(
		label = entry.name, 
		assets = entry.assets, liabilities = entry.liabilities, 
		net = entry.assets - entry.liabilities))

def printBalanceSheet(balanceSheetEntries, label):
	print("{label:>20s}: {assets:<13s} | {liabilities:<13s} || {net:<13s}".format(
		label = label, 
		assets = "Assets", liabilities = "Liabilities", 
		net = "Net value"))
		
	totals = BalanceSheetEntry("TOTALS")
	for entry in balanceSheetEntries:
		printBalanceSheetEntry(entry)
		totals.assets += entry.assets
		totals.liabilities += entry.liabilities

	totalsWithoutRekts = copy.copy(totals)
	totalsWithoutRekts.name = "TOTALS w/o Rekt CDPs"
	totalsWithoutRekts.assets -= balanceSheetEntries[-1].assets
	totalsWithoutRekts.liabilities -= balanceSheetEntries[-1].liabilities
		
	print("--------------------------------------------------------------------")
	printBalanceSheetEntry(totals)
	printBalanceSheetEntry(totalsWithoutRekts)
	print("====================================================================\n")
	return totalsWithoutRekts

# Reserves in the internal pools count as assets for Root.
balancesheetPoolReserves = BalanceSheetEntry("Pool reserves", totalPoolReservesValue, 0)
balanceSheetEntries = [balancesheetPoolReserves] + balanceSheetEntriesByRiskClass

print("*** Root Finance assets/liabilities according to CDPs and reserves in pools ***\n")
print("IMPORTANT: Only assets/liabilities in CDPs and reserve pools are considered here.\n"
	"Additional assets may exist e.g. in treasury accounts.\n")


printBalanceSheet(balanceSheetEntries, "Summary")

balanceSheetEntries_allWithoutRekts_byAsset = []
for asset in cdpAssets:
	balanceSheetEntriesByRiskClass_currentAsset = [
	BalanceSheetEntry("Healthy CDPs"),
	BalanceSheetEntry("Risky CDPs"),
	BalanceSheetEntry("Rekt CDPs"), ]
	
	for cdp in cdps:
		entry = balanceSheetEntriesByRiskClass_currentAsset[cdp.riskClass]
		balances = cdp.balanceByAddress[asset.address]
		entry.add(-balances.value_loan, balances.value_collateral)
		
	
	totalPoolReservesValue_currentAsset = totalPoolReservesValue_byAssetAddress[asset.address]
	balancesheetPoolReserves_currentAsset = BalanceSheetEntry("Pool reserves", totalPoolReservesValue_currentAsset, 0)
		
	balanceSheetEntries_currentAsset = []
	balanceSheetEntries_currentAsset.append(balancesheetPoolReserves_currentAsset)
	balanceSheetEntries_currentAsset.extend(balanceSheetEntriesByRiskClass_currentAsset)
	
	totalsWithoutRekts_currentAsset = printBalanceSheet(balanceSheetEntries_currentAsset, asset.ticker)
	totalsWithoutRekts_currentAsset.name = asset.ticker
	balanceSheetEntries_allWithoutRekts_byAsset.append(totalsWithoutRekts_currentAsset)


printBalanceSheet(balanceSheetEntries_allWithoutRekts_byAsset, "TotalWithoutRekts")


print("------------------------------")
filenameOutput = args.output_file
with open(filenameOutput, mode="w", newline="", encoding="utf-8") as csvfile:
	csvout = csv.writer(csvfile)
	csvout.writerow(cdps[0].csvHeaders())
	csvout.writerows([cdp.csvValues() for cdp in cdps])
print(f"{filenameOutput} written.")




